// ข้อมูลจำลองตามโครงสร้าง Google Sheet สำหรับระบบคณะสงฆ์จังหวัดพระนครศรีอยุธยา (ข้อมูลจำลอง)
const SANGHA_DATA = {
  provinceName: "จังหวัดพระนครศรีอยุธยา (ข้อมูลจำลอง)",
  statistics: {
    totalTemples: 524,
    totalMonks: 3820,
    totalNovices: 1250,
    totalDistricts: 16
  },
  districts: [
    {
      name: "อ.พระนครศรีอยุธยา",
      subdistricts: ["ประตูชัย", "กะมัง", "หอรัตนไชย", "หัวรอ", "กุฎีดาว", "พลับพลาไชย", "ท่าวาสุกรี", "ไผ่ลิง", "ปากกราน", "ภูเขาทอง", "สำเภาล่ม", "สวนพริก", "คลองตะเคียน", "วัดตูม", "หันตรา", "ลุมพลี", "บ้านใหม่", "บ้านเกาะ", "คลองสวนพลู", "คลองสระบัว", "เกาะเรียน", "บ้านป้อม", "บ้านรุน"]
    },
    {
      name: "อ.ท่าเรือ",
      subdistricts: ["ท่าเรือ", "จำปา", "ท่าหลวง", "บ้านร่อม", "ศาลาลอย", "วังแดง", "โพธิ์เอน", "ปากท่า", "หนองขนาก", "ท่าเจ้าสนุก"]
    },
    {
      name: "อ.นครหลวง",
      subdistricts: ["นครหลวง", "ท่าช้าง", "บ่อโพง", "บ้านชุ้ง", "ปากจั่น", "แม่ลา", "หนองปลิง", "คลองสะแก", "สามไถ", "พระนอน", "ฉลอง", "ท่าคล้อ"]
    },
    {
      name: "อ.บางไทร",
      subdistricts: ["บางไทร", "บางพลี", "สนามชัย", "บ้านแป้ง", "หน้าไม้", "บางยี่โท", "แคตก", "แคออก", "เชียงรากน้อย", "โพแตง", "บ้านกลึง", "ราชคราม", "ช้างใหญ่", "ไม้ตรา", "บ้านม้า", "บ้านเกาะ", "ช่างเหล็ก", "ห่อหมก", "ไผ่พระ", "กบเจา", "สารี", "เชียงรากใหญ่"]
    },
    {
      name: "อ.บางบาล",
      subdistricts: ["บางบาล", "กบเจา", "บ้านคลัง", "พระขาว", "ทางช้าง", "น้ำเต้า", "วัดยม", "ไทรน้อย", "มหาพราหมณ์", "สะพานไทย", "มกุฎ", "บางหลวงโดด", "บางหลวง", "บางชะนี", "บ้านกุ่ม", "บ้านขวาง"]
    },
    {
      name: "อ.บางปะอิน",
      subdistricts: ["บ้านเลน", "เชียงรากน้อย", "สามเรือน", "เกาะเกิด", "บ้านโพ", "บ้านกรด", "บางกระสั้น", "คลองจิก", "บ้านหว้า", "วัดยม", "บางประแดง", "ขนอนหลวง", "บ้านสร้าง", "ตลาดเกรียบ", "ตลิ่งชัน", "คุ้งลาน", "บ้านพลับ", "บ้านแป้ง"]
    }
  ],
  hierarchy: {
    governor: {
      name: "พระธรรมรัตนมงคล (แฉล้ม เขมปญฺโญ)",
      position: "เจ้าคณะจังหวัดพระนครศรีอยุธยา",
      temple: "วัดพนัญเชิงวรวิหาร",
      district: "อ.พระนครศรีอยุธยา",
      subdistrict: "คลองสวนพลู",
      rank: "พระราชาคณะชั้นธรรม",
      imageColor: "from-amber-700 to-amber-900",
      details: "เจ้าคณะจังหวัดพระนครศรีอยุธยา และเจ้าอาวาสวัดพนัญเชิงวรวิหาร พระอารามหลวงชั้นโท คอยดูแลปกครองคณะสงฆ์ในเขตปกครองทั้งหมด 16 อำเภอ"
    },
    deputies: [
      {
        name: "พระราชพัฒนาภรณ์ (สมชาย เกสโร)",
        position: "รองเจ้าคณะจังหวัดพระนครศรีอยุธยา รูปที่ 1",
        temple: "วัดท่าการ้อง",
        district: "อ.พระนครศรีอยุธยา",
        subdistrict: "บ้านป้อม",
        rank: "พระราชาคณะชั้นราช",
        imageColor: "from-amber-600 to-amber-800",
        details: "ดูแลรับผิดชอบงานฝ่ายสาธารณูปการและการสาธารณสงเคราะห์ของจังหวัด"
      },
      {
        name: "พระศรีปริยัติเมธี (สมพงษ์ สุตาลงฺกprocessing, ป.ธ.9)",
        position: "รองเจ้าคณะจังหวัดพระนครศรีอยุธยา รูปที่ 2",
        temple: "วัดกษัตราธิราชวรวิหาร",
        district: "อ.พระนครศรีอยุธยา",
        subdistrict: "บ้านป้อม",
        rank: "พระราชาคณะชั้นสามัญเปรียญ",
        imageColor: "from-amber-600 to-amber-800",
        details: "ดูแลฝ่ายการศึกษาปริยัติธรรม แผนกธรรม-บาลี ของคณะสงฆ์จังหวัด"
      }
    ]
  },
  monks: [
    {
      id: "monk-01",
      image: "",
      title: "พระธรรมรัตนมงคล",
      firstName: "แฉล้ม",
      lastName: "เขมปญฺโญ",
      chaya: "เขมปญฺโญ",
      nickname: "หลวงพ่อแฉล้ม",
      idCard: "3-1401-xxxxx-92-1",
      birthDate: "15 มกราคม 2490",
      phone: "081-234-5678",
      lineId: "chalaem.k",
      ordinationDate: "20 พฤษภาคม 2511",
      upajjhaya: "พระอุปัชฌาย์จำลอง",
      vassa: 58,
      residingTemple: "วัดพนัญเชิงวรวิหาร",
      affiliatedTemple: "วัดพนัญเชิงวรวิหาร",
      subdistrict: "คลองสวนพลู",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "เจ้าคณะจังหวัด",
      upajjhayaStatus: "พระอุปัชฌาย์ประเภทวิสามัญ",
      upajjhayaCode: "UP-1401-001",
      otherPosition: "ที่ปรึกษามหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย",
      rajathinnanam: "พระธรรมรัตนมงคล",
      rankClass: "พระราชาคณะชั้นธรรม",
      faction: "มหานิกาย",
      education: "ปริญญาโท (พุทธศาสนมหาบัณฑิต)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "เปรียญธรรม 6 ประโยค"
    },
    {
      id: "monk-02",
      image: "",
      title: "พระราชพัฒนาภรณ์",
      firstName: "สมชาย",
      lastName: "เกสโร",
      chaya: "เกสโร",
      nickname: "หลวงพ่อสมชาย",
      idCard: "3-1401-xxxxx-11-2",
      birthDate: "10 พฤศจิกายน 2498",
      phone: "089-876-5432",
      lineId: "somchaitkr",
      ordinationDate: "12 กรกฎาคม 2519",
      upajjhaya: "พระอธิการอุดม วัดท่าการ้อง",
      vassa: 50,
      residingTemple: "วัดท่าการ้อง",
      affiliatedTemple: "วัดท่าการ้อง",
      subdistrict: "บ้านป้อม",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "รองเจ้าคณะจังหวัด",
      upajjhayaStatus: "พระอุปัชฌาย์ประเภทสามัญ",
      upajjhayaCode: "UP-1401-002",
      otherPosition: "",
      rajathinnanam: "พระราชพัฒนาภรณ์",
      rankClass: "พระราชาคณะชั้นราช",
      faction: "มหานิกาย",
      education: "ปริญญาตรี (รัฐประศาสนศาสตร์)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "ไม่มี"
    },
    {
      id: "monk-03",
      image: "",
      title: "พระศรีปริยัติเมธี",
      firstName: "สมพงษ์",
      lastName: "สุตาลงฺกprocessing",
      chaya: "สุตาลงฺกprocessing",
      nickname: "พระมหาสมพงษ์",
      idCard: "3-1401-xxxxx-45-6",
      birthDate: "24 เมษายน 2505",
      phone: "083-456-7890",
      lineId: "sompong.p9",
      ordinationDate: "23 พฤษภาคม 2526",
      upajjhaya: "พระราชธานินทร์ วัดกษัตราธิราชวรวิหาร",
      vassa: 43,
      residingTemple: "วัดกษัตราธิราชวรวิหาร",
      affiliatedTemple: "วัดกษัตราธิราชวรวิหาร",
      subdistrict: "บ้านป้อม",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "รองเจ้าคณะจังหวัด",
      upajjhayaStatus: "พระอุปัชฌาย์ประเภทวิสามัญ",
      upajjhayaCode: "UP-1401-003",
      otherPosition: "ผู้อำนวยการศูนย์บาลีศึกษาจังหวัด",
      rajathinnanam: "พระศรีปริยัติเมธี",
      rankClass: "พระราชาคณะชั้นสามัญ",
      faction: "มหานิกาย",
      education: "ปริญญาเอก (สาขาพุทธศาสตร์)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "เปรียญธรรม 9 ประโยค"
    },
    {
      id: "monk-04",
      image: "",
      title: "พระครูวิมลธรรมวิจิตร",
      firstName: "สุรเดช",
      lastName: "ธมฺมรโต",
      chaya: "ธมฺมรโต",
      nickname: "พระครูเดช",
      idCard: "3-1402-xxxxx-33-4",
      birthDate: "8 กันยายน 2511",
      phone: "084-567-8901",
      lineId: "suradech.vml",
      ordinationDate: "15 มิถุนายน 2532",
      upajjhaya: "พระเทพมงคลรังสี วัดมหาธาตุวราราม",
      vassa: 37,
      residingTemple: "วัดราษฎร์บำรุง",
      affiliatedTemple: "วัดราษฎร์บำรุง",
      subdistrict: "หัวรอ",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "เจ้าคณะอำเภอ",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "",
      rajathinnanam: "พระครูวิมลธรรมวิจิตร",
      rankClass: "พระครูสัญญาบัตร",
      faction: "มหานิกาย",
      education: "ปริญญาตรี (การจัดการเชิงพุทธ)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "เปรียญธรรม 3 ประโยค"
    },
    {
      id: "monk-05",
      image: "",
      title: "พระครูสิริปัญญากร",
      firstName: "บุญมี",
      lastName: "ญาณวโร",
      chaya: "ญาณวโร",
      nickname: "หลวงตานึก",
      idCard: "3-1403-xxxxx-22-1",
      birthDate: "5 มีนาคม 2513",
      phone: "085-678-9012",
      lineId: "boonmee.tr",
      ordinationDate: "10 พฤษภาคม 2534",
      upajjhaya: "พระราชปัญญามุนี วัดสว่างอารมณ์",
      vassa: 35,
      residingTemple: "วัดรัตนคีรี",
      affiliatedTemple: "วัดรัตนคีรี",
      subdistrict: "จำปา",
      district: "อ.ท่าเรือ",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "เจ้าคณะอำเภอ",
      upajjhayaStatus: "พระอุปัชฌาย์ประเภทสามัญ",
      upajjhayaCode: "UP-1403-001",
      otherPosition: "",
      rajathinnanam: "พระครูสิริปัญญากร",
      rankClass: "พระครูสัญญาบัตร",
      faction: "มหานิกาย",
      education: "ปริญญาตรี (รัฐศาสตร์)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "ไม่มี"
    },
    {
      id: "monk-06",
      image: "",
      title: "พระครูเกษมศีลคุณ",
      firstName: "วิชัย",
      lastName: "เขมธโร",
      chaya: "เขมธโร",
      nickname: "พระอาจารย์วิชัย",
      idCard: "3-1404-xxxxx-88-7",
      birthDate: "12 กรกฎาคม 2516",
      phone: "086-789-0123",
      lineId: "wichai.kem",
      ordinationDate: "20 มิถุนายน 2537",
      upajjhaya: "พระครูพิพิธวิหารการ วัดยม",
      vassa: 32,
      residingTemple: "วัดยม",
      affiliatedTemple: "วัดยม",
      subdistrict: "บ่อโพง",
      district: "อ.นครหลวง",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "เจ้าคณะอำเภอ",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "",
      rajathinnanam: "พระครูเกษมศีลคุณ",
      rankClass: "พระครูสัญญาบัตร",
      faction: "มหานิกาย",
      education: "ปริญญาโท (การบริหารการศึกษา)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "เปรียญธรรม 4 ประโยค"
    },
    {
      id: "monk-07",
      image: "",
      title: "พระครูพิพัฒน์สารธรรม",
      firstName: "สมชาย",
      lastName: "สารโธ",
      chaya: "สารโธ",
      nickname: "หลวงพี่ชาย",
      idCard: "3-1405-xxxxx-55-4",
      birthDate: "18 ตุลาคม 2519",
      phone: "087-890-1234",
      lineId: "somchai.saratho",
      ordinationDate: "5 เมษายน 2540",
      upajjhaya: "พระครูวิสุทธิปัญญาภรณ์ วัดสนามชัย",
      vassa: 29,
      residingTemple: "วัดบางพลี",
      affiliatedTemple: "วัดบางพลี",
      subdistrict: "บางพลี",
      district: "อ.บางไทร",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "เจ้าคณะตำบล",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "",
      rajathinnanam: "พระครูพิพัฒน์สารธรรม",
      rankClass: "พระครูสัญญาบัตร",
      faction: "มหานิกาย",
      education: "มัธยมศึกษาตอนปลาย",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "ไม่มี"
    },
    {
      id: "monk-08",
      image: "",
      title: "พระมหาธวัชชัย",
      firstName: "ธวัชชัย",
      lastName: "ชยาภินนฺโท",
      chaya: "ชยาภินนฺโท",
      nickname: "มหาธวัช",
      idCard: "3-1401-xxxxx-19-0",
      birthDate: "3 สิงหาคม 2527",
      phone: "084-654-3210",
      lineId: "thawatchai.p7",
      ordinationDate: "15 พฤษภาคม 2548",
      upajjhaya: "พระธรรมรัตนมงคล วัดพนัญเชิงวรวิหาร",
      vassa: 21,
      residingTemple: "วัดกษัตราธิราชวรวิหาร",
      affiliatedTemple: "วัดกษัตราธิราชวรวิหาร",
      subdistrict: "บ้านป้อม",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "รองเจ้าอาวาส",
      sanghaPosition: "เลขานุการเจ้าคณะอำเภอ",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "ครูสอนพระปริยัติธรรม",
      rajathinnanam: "",
      rankClass: "พระเปรียญธรรม 7 ประโยค",
      faction: "มหานิกาย",
      education: "ปริญญาโท (ภาษาศาสตร์)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "เปรียญธรรม 7 ประโยค"
    },
    {
      id: "monk-09",
      image: "",
      title: "พระครูสังฆรักษ์ธีรยุทธ",
      firstName: "ธีรยุทธ",
      lastName: "ขนฺติธโร",
      chaya: "ขนฺติธโร",
      nickname: "หลวงพี่เต๋า",
      idCard: "3-1406-xxxxx-22-3",
      birthDate: "27 ธันวาคม 2529",
      phone: "083-765-4321",
      lineId: "theerayuth.kt",
      ordinationDate: "28 มีนาคม 2550",
      upajjhaya: "พระครูวินัยธรวิชัย วัดยม",
      vassa: 19,
      residingTemple: "วัดยม",
      affiliatedTemple: "วัดยม",
      subdistrict: "พระขาว",
      district: "อ.บางบาล",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "ผู้ช่วยเจ้าอาวาส",
      sanghaPosition: "เจ้าคณะตำบล",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "",
      rajathinnanam: "",
      rankClass: "พระครูฐานานุกรม",
      faction: "มหานิกาย",
      education: "ปริญญาตรี (คอมพิวเตอร์เพื่อการศึกษา)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "ไม่มี"
    },
    {
      id: "monk-10",
      image: "",
      title: "พระสมุห์อรรถพล",
      firstName: "อรรถพล",
      lastName: "กิตฺติปาโล",
      chaya: "กิตฺติปาโล",
      nickname: "พระอรรถ",
      idCard: "3-1401-xxxxx-77-6",
      birthDate: "14 พฤษภาคม 2531",
      phone: "082-876-5432",
      lineId: "attapol.kitti",
      ordinationDate: "1 พฤษภาคม 2552",
      upajjhaya: "พระราชพัฒนาภรณ์ วัดท่าการ้อง",
      vassa: 17,
      residingTemple: "วัดกุฎีดาว",
      affiliatedTemple: "วัดกุฎีดาว",
      subdistrict: "กุฎีดาว",
      district: "อ.พระนครศรีอยุธยา",
      province: "พระนครศรีอยุธยา",
      region: "ภาค 2",
      templePosition: "เจ้าอาวาส",
      sanghaPosition: "ไม่มี",
      upajjhayaStatus: "ไม่มี",
      upajjhayaCode: "",
      otherPosition: "พระวิทยากรเผยแผ่ธรรมะ",
      rajathinnanam: "",
      rankClass: "พระครูฐานานุกรม",
      faction: "มหานิกาย",
      education: "ปริญญาตรี (สังคมศาสตร์)",
      dhammaEducation: "นักธรรมเอก",
      paliEducation: "ไม่มี"
    }
  ],
  events: [
    {
      date: "วันอาทิตย์ที่ 21 มิถุนายน 2569",
      title: "วันพระ (ขึ้น ๘ ค่ำ เดือน ๘)",
      type: "holy-day",
      description: "ทำบุญตักบาตร ฟังพระธรรมเทศนา ณ วัดใกล้บ้านในเขตพื้นที่"
    },
    {
      date: "วันอาทิตย์ที่ 28 มิถุนายน 2569",
      title: "วันอาสาฬหบูชา (ขึ้น ๑๕ ค่ำ เดือน ๘)",
      type: "holy-day",
      description: "พิธีเวียนเทียน ถวายเทียนพรรษา และเทศนาธรรมใหญ่ประจำปี ณ วัดพนัญเชิงวรวิหาร และวัดต่างๆ ทุกตำบล"
    },
    {
      date: "วันพุธที่ 1 กรกฎาคม 2569",
      title: "การประชุมคณะสงฆ์จังหวัดพระนครศรีอยุธยา ประจำเดือน",
      type: "meeting",
      description: "ประชุมพระสังฆาธิการระดับเจ้าคณะตำบลและเจ้าคณะอำเภอ ณ ศาลาการเปรียญวัดพนัญเชิงวรวิหาร เวลา 13.00 น."
    },
    {
      date: "วันเสาร์ที่ 11 กรกฎาคม 2569",
      title: "โครงการฝึกอบรมบาลีก่อนสอบคณะสงฆ์ ภาค 2",
      type: "training",
      description: "โครงการส่งเสริมและอบรมทบทวนภาษาบาลีสำหรับภิกษุสามเณรผู้เตรียมตัวสอบนักธรรม-บาลี ณ ศูนย์บาลีศึกษา วัดกษัตราธิราชวรวิหาร"
    }
  ],
  temples: [
    { name: "วัดพนัญเชิงวรวิหาร", type: "พระอารามหลวงชั้นโท", district: "อ.พระนครศรีอยุธยา", subdistrict: "คลองสวนพลู", abbot: "พระธรรมรัตนมงคล" },
    { name: "วัดท่าการ้อง", type: "วัดราษฎร์", district: "อ.พระนครศรีอยุธยา", subdistrict: "บ้านป้อม", abbot: "พระราชพัฒนาภรณ์" },
    { name: "วัดกษัตราธิราชวรวิหาร", type: "พระอารามหลวงชั้นตรี", district: "อ.พระนครศรีอยุธยา", subdistrict: "บ้านป้อม", abbot: "พระศรีปริยัติเมธี" },
    { name: "วัดราษฎร์บำรุง", type: "วัดราษฎร์", district: "อ.พระนครศรีอยุธยา", subdistrict: "หัวรอ", abbot: "พระครูวิมลธรรมวิจิตร" },
    { name: "วัดรัตนคีรี", type: "วัดราษฎร์", district: "อ.ท่าเรือ", subdistrict: "จำปา", abbot: "พระครูสิริปัญญากร" },
    { name: "วัดยม", type: "วัดราษฎร์", district: "อ.นครหลวง", subdistrict: "บ่อโพง", abbot: "พระครูเกษมศีลคุณ" },
    { name: "วัดบางพลี", type: "วัดราษฎร์", district: "อ.บางไทร", subdistrict: "บางพลี", abbot: "พระครูพิพัฒน์สารธรรม" },
    { name: "วัดกุฎีดาว", type: "วัดราษฎร์", district: "อ.พระนครศรีอยุธยา", subdistrict: "กุฎีดาว", abbot: "พระสมุห์อรรถพล" }
  ]
};
